/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blog: Blog;
    filieres: Filiere;
    universites: Universite;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    filieres: FilieresSelect<false> | FilieresSelect<true>;
    universites: UniversitesSelect<false> | UniversitesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  slug: string;
  cover: string | Media;
  shortDescription: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  category?: string | null;
  creator: string | User;
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filieres".
 */
export interface Filiere {
  id: string;
  nomDeFiliere: string;
  slug: string;
  descriptionCourte: string;
  salaireMoyen?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  longDescription_html?: string | null;
  category: 'Technologie' | 'Économie' | 'Agriculture' | 'Santé' | 'Sciences Sociales';
  duration: string;
  bacRequired: ('A' | 'C' | 'D' | 'F1' | 'F2' | 'F3' | 'G1' | 'G2')[];
  locations?: ('Niamey' | 'Maradi' | 'Zinder' | 'Tahoua' | 'Agadez' | 'Dosso' | 'Diffa' | 'Tillabéri')[] | null;
  prerequisites?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  careerOpportunities?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  universities?: (string | Universite)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universites".
 */
export interface Universite {
  id: string;
  name: string;
  slug: string;
  type?: string | null;
  region?: ('Niamey' | 'Zinder' | 'Maradi' | 'Tahaoua' | 'Agadez' | 'Tillabery' | 'Dosso' | 'Diffa') | null;
  /**
   * Entrer un autre pays si différent de Niger
   */
  country?: string | null;
  educationSystem?: string | null;
  graduatesCount?: number | null;
  logo?: (string | null) | Media;
  bannerImage?: (string | null) | Media;
  motto?: string | null;
  cycleDuration?:
    | {
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  programs?: (string | Filiere)[] | null;
  academicResults?: string | null;
  admissionRequirements?:
    | {
        requirement?: string | null;
        id?: string | null;
      }[]
    | null;
  tuitionFees?:
    | {
        program?: string | null;
        amount?: string | null;
        id?: string | null;
      }[]
    | null;
  accreditations?: string | null;
  authorization?: string | null;
  campusResources?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        partner?: string | null;
        id?: string | null;
      }[]
    | null;
  studentActivities?:
    | {
        activity?: string | null;
        id?: string | null;
      }[]
    | null;
  clubs?:
    | {
        club?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        src?: string | null;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        src?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'filieres';
        value: string | Filiere;
      } | null)
    | ({
        relationTo: 'universites';
        value: string | Universite;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  shortDescription?: T;
  content?: T;
  content_html?: T;
  category?: T;
  creator?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filieres_select".
 */
export interface FilieresSelect<T extends boolean = true> {
  nomDeFiliere?: T;
  slug?: T;
  descriptionCourte?: T;
  salaireMoyen?: T;
  longDescription?: T;
  longDescription_html?: T;
  category?: T;
  duration?: T;
  bacRequired?: T;
  locations?: T;
  prerequisites?:
    | T
    | {
        item?: T;
        id?: T;
      };
  careerOpportunities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  universities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universites_select".
 */
export interface UniversitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  region?: T;
  country?: T;
  educationSystem?: T;
  graduatesCount?: T;
  logo?: T;
  bannerImage?: T;
  motto?: T;
  cycleDuration?:
    | T
    | {
        value?: T;
        id?: T;
      };
  programs?: T;
  academicResults?: T;
  admissionRequirements?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  tuitionFees?:
    | T
    | {
        program?: T;
        amount?: T;
        id?: T;
      };
  accreditations?: T;
  authorization?: T;
  campusResources?:
    | T
    | {
        item?: T;
        id?: T;
      };
  partners?:
    | T
    | {
        partner?: T;
        id?: T;
      };
  studentActivities?:
    | T
    | {
        activity?: T;
        id?: T;
      };
  clubs?:
    | T
    | {
        club?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        src?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        src?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}